import io
import html
import xml.sax.saxutils as saxutils
from datetime import datetime, timezone
from typing import List, Dict, Any, Optional

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    KeepTogether,
    HRFlowable,
)
from reportlab.pdfgen import canvas

from app.schemas.report import DFIRReportDTO


def _clean_xml(val: Any) -> str:
    """
    Clean and escape strings for ReportLab Platypus Paragraph XML engine.
    Unescapes any pre-existing HTML/XML entities first to prevent double-escaping (e.g. &amp;amp;).
    """
    if val is None:
        return ""
    s = str(val)
    # Unescape existing HTML/XML entities to baseline
    s = html.unescape(s)
    # Escape for ReportLab XML parser (&, <, >)
    return saxutils.escape(s)


class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to dynamically compute and render total page count
    along with running header and footer.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica-Bold", 8)
        self.setFillColor(colors.HexColor("#475569"))

        # Top Running Header (Pages > 1)
        if self._pageNumber > 1:
            self.drawString(36, 11 * inch - 28, "AEGIS DIGITAL FORENSICS & INCIDENT RESPONSE (DFIR) REPORT")
            self.drawRightString(8.5 * inch - 36, 11 * inch - 28, "CONFIDENTIAL // TLP:AMBER")
            self.setStrokeColor(colors.HexColor("#CBD5E1"))
            self.setLineWidth(0.5)
            self.line(36, 11 * inch - 32, 8.5 * inch - 36, 11 * inch - 32)

        # Bottom Running Footer (All Pages)
        self.setStrokeColor(colors.HexColor("#CBD5E1"))
        self.setLineWidth(0.5)
        self.line(36, 36, 8.5 * inch - 36, 36)

        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B"))
        self.drawString(36, 24, "Generated by AEGIS Forensic Intelligence Platform • Automated Cryptographic Evidence Seal")
        self.drawRightString(8.5 * inch - 36, 24, f"Page {self._pageNumber} of {page_count}")
        self.restoreState()


class PDFReportExporter:
    """
    High-fidelity PDF Report Generator for AEGIS DFIR Executive Reports.
    """

    def __init__(self, report: DFIRReportDTO):
        self.report = report
        self.styles = getSampleStyleSheet()
        self._init_custom_styles()

    def _init_custom_styles(self):
        # Color definitions
        self.c_primary = colors.HexColor("#0B1120")
        self.c_navy = colors.HexColor("#1E293B")
        self.c_blue = colors.HexColor("#2563EB")
        self.c_red = colors.HexColor("#DC2626")
        self.c_amber = colors.HexColor("#D97706")
        self.c_emerald = colors.HexColor("#059669")
        self.c_gray_bg = colors.HexColor("#F8FAFC")
        self.c_border = colors.HexColor("#E2E8F0")
        self.c_text = colors.HexColor("#0F172A")
        self.c_muted = colors.HexColor("#64748B")

        # Custom Paragraph Styles
        self.styles.add(ParagraphStyle(
            name="ReportTitle",
            fontName="Helvetica-Bold",
            fontSize=18,
            leading=22,
            textColor=self.c_primary,
            spaceAfter=4,
        ))
        self.styles.add(ParagraphStyle(
            name="ReportSubtitle",
            fontName="Helvetica-Bold",
            fontSize=10,
            leading=14,
            textColor=self.c_blue,
            spaceAfter=10,
        ))
        self.styles.add(ParagraphStyle(
            name="SectionHeading",
            fontName="Helvetica-Bold",
            fontSize=12,
            leading=16,
            textColor=self.c_navy,
            spaceBefore=12,
            spaceAfter=6,
            keepWithNext=True,
        ))
        self.styles.add(ParagraphStyle(
            name="BodyDark",
            fontName="Helvetica",
            fontSize=9,
            leading=13,
            textColor=self.c_text,
        ))
        self.styles.add(ParagraphStyle(
            name="BodyDarkBold",
            fontName="Helvetica-Bold",
            fontSize=9,
            leading=13,
            textColor=self.c_text,
        ))
        self.styles.add(ParagraphStyle(
            name="BodyMuted",
            fontName="Helvetica",
            fontSize=8,
            leading=11,
            textColor=self.c_muted,
        ))
        self.styles.add(ParagraphStyle(
            name="MonoText",
            fontName="Courier",
            fontSize=8,
            leading=10,
            textColor=self.c_text,
        ))
        self.styles.add(ParagraphStyle(
            name="MonoTextBold",
            fontName="Courier-Bold",
            fontSize=8,
            leading=10,
            textColor=self.c_text,
        ))
        self.styles.add(ParagraphStyle(
            name="TableHeader",
            fontName="Helvetica-Bold",
            fontSize=8,
            leading=10,
            textColor=colors.white,
            alignment=0,
        ))
        self.styles.add(ParagraphStyle(
            name="TableCell",
            fontName="Helvetica",
            fontSize=8,
            leading=11,
            textColor=self.c_text,
        ))
        self.styles.add(ParagraphStyle(
            name="TableCellMono",
            fontName="Courier",
            fontSize=7.5,
            leading=9.5,
            textColor=self.c_text,
        ))
        self.styles.add(ParagraphStyle(
            name="TableCellIocMono",
            fontName="Courier",
            fontSize=7,
            leading=8.5,
            textColor=self.c_text,
        ))
        self.styles.add(ParagraphStyle(
            name="BadgeP0",
            fontName="Helvetica-Bold",
            fontSize=8,
            leading=10,
            textColor=self.c_red,
        ))
        self.styles.add(ParagraphStyle(
            name="BadgeP1",
            fontName="Helvetica-Bold",
            fontSize=8,
            leading=10,
            textColor=self.c_amber,
        ))
        self.styles.add(ParagraphStyle(
            name="BadgeP2",
            fontName="Helvetica-Bold",
            fontSize=8,
            leading=10,
            textColor=self.c_blue,
        ))

    def generate_pdf(self) -> bytes:
        """Build the full PDF document in memory and return binary bytes."""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            leftMargin=36,
            rightMargin=36,
            topMargin=44,
            bottomMargin=44,
        )

        story = []
        printable_width = 8.5 * inch - 72  # 540 pt

        # 1. Header Banner & Case Metadata Box
        story.extend(self._build_header_section(printable_width))
        story.append(Spacer(1, 10))

        # 2. Executive Summary & Verdict Gauges
        story.extend(self._build_executive_section(printable_width))
        story.append(Spacer(1, 10))

        # 3. MITRE ATT&CK Matrix Alignment
        story.extend(self._build_mitre_section(printable_width))
        story.append(Spacer(1, 10))

        # 4. Prioritized SOC Remediation Playbook
        story.extend(self._build_remediation_section(printable_width))
        story.append(Spacer(1, 10))

        # 5. Evidentiary Findings & Relay Route
        story.extend(self._build_findings_and_route_section(printable_width))
        story.append(Spacer(1, 10))

        # 6. IoC Appendix
        story.extend(self._build_ioc_section(printable_width))

        # Build document with running header/footer
        doc.build(story, canvasmaker=NumberedCanvas)
        buffer.seek(0)
        return buffer.getvalue()

    def _build_header_section(self, width: float) -> List[Any]:
        elements = []

        # Title & Reference Bar
        elements.append(Paragraph("AEGIS DIGITAL FORENSICS & INCIDENT RESPONSE REPORT", self.styles["ReportTitle"]))
        case_ref = _clean_xml(self.report.case_reference)
        rpt_id = _clean_xml(self.report.report_id)
        gen_at = _clean_xml(self.report.generated_at[:19].replace('T', ' '))
        elements.append(Paragraph(
            f"Case Reference: <strong>{case_ref}</strong> • Report ID: <strong>{rpt_id}</strong> • Generated: <strong>{gen_at} UTC</strong>",
            self.styles["ReportSubtitle"]
        ))

        # Metadata Table
        meta = self.report.email_metadata
        exec_sum = self.report.executive_summary

        sev_color = "#DC2626" if exec_sum.risk_score >= 80 else "#D97706" if exec_sum.risk_score >= 50 else "#059669"

        from_name_clean = _clean_xml(meta.get("from_name") or "")
        from_email_clean = _clean_xml(meta.get("from_email", "Unknown"))
        from_cell = f"{from_name_clean} &lt;{from_email_clean}&gt;" if from_name_clean else from_email_clean

        sha_clean = _clean_xml(meta.get("sha256", "N/A"))
        sha_display = f"{sha_clean[:32]}..." if len(sha_clean) > 32 else sha_clean
        filename_clean = _clean_xml(meta.get("filename", "email.eml"))

        meta_data = [
            [
                Paragraph("<strong>From:</strong>", self.styles["BodyDarkBold"]),
                Paragraph(from_cell, self.styles["BodyDark"]),
                Paragraph("<strong>Threat Verdict:</strong>", self.styles["BodyDarkBold"]),
                Paragraph(f"<font color='{sev_color}'><strong>{_clean_xml(exec_sum.verdict)} ({exec_sum.risk_score}/100)</strong></font>", self.styles["BodyDarkBold"]),
            ],
            [
                Paragraph("<strong>To:</strong>", self.styles["BodyDarkBold"]),
                Paragraph(_clean_xml(meta.get("to_email", "N/A")), self.styles["BodyDark"]),
                Paragraph("<strong>Classification:</strong>", self.styles["BodyDarkBold"]),
                Paragraph(f"<strong>{_clean_xml(exec_sum.classification)}</strong>", self.styles["BodyDark"]),
            ],
            [
                Paragraph("<strong>Subject:</strong>", self.styles["BodyDarkBold"]),
                Paragraph(_clean_xml(meta.get("subject", "No Subject")), self.styles["BodyDark"]),
                Paragraph("<strong>AI Confidence:</strong>", self.styles["BodyDarkBold"]),
                Paragraph(f"<strong>{exec_sum.ai_confidence * 100:.1f}%</strong>", self.styles["BodyDark"]),
            ],
            [
                Paragraph("<strong>File / SHA256:</strong>", self.styles["BodyDarkBold"]),
                Paragraph(f"<font size='7'>{filename_clean}<br/>SHA256: {sha_display}</font>", self.styles["TableCellMono"]),
                Paragraph("<strong>Origin IP:</strong>", self.styles["BodyDarkBold"]),
                Paragraph(_clean_xml(meta.get("origin_ip") or "N/A"), self.styles["TableCellMono"]),
            ],
        ]

        t = Table(meta_data, colWidths=[70, 210, 95, 165])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), self.c_gray_bg),
            ("BOX", (0, 0), (-1, -1), 1, self.c_border),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, self.c_border),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ]))
        elements.append(t)
        return elements

    def _build_executive_section(self, width: float) -> List[Any]:
        elements = []
        elements.append(Paragraph("1. Executive Summary & Assessment", self.styles["SectionHeading"]))

        exec_sum = self.report.executive_summary
        elements.append(Paragraph(_clean_xml(exec_sum.narrative), self.styles["BodyDark"]))
        elements.append(Spacer(1, 4))

        # Key Takeaways Box
        takeaways_html = "<br/>".join([f"• {_clean_xml(t)}" for t in exec_sum.key_takeaways])
        box_data = [[
            Paragraph(f"<strong>Key Takeaways & Attack Vector:</strong><br/>{takeaways_html}", self.styles["BodyDark"])
        ]]
        t = Table(box_data, colWidths=[width])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#EFF6FF")),
            ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#BFDBFE")),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ]))
        elements.append(t)
        return elements

    def _build_mitre_section(self, width: float) -> List[Any]:
        elements = []
        elements.append(Paragraph("2. MITRE ATT&CK Matrix Alignment", self.styles["SectionHeading"]))

        headers = [
            Paragraph("ID", self.styles["TableHeader"]),
            Paragraph("Technique Name", self.styles["TableHeader"]),
            Paragraph("Tactic", self.styles["TableHeader"]),
            Paragraph("Confidence", self.styles["TableHeader"]),
            Paragraph("Matched Evidence / Context", self.styles["TableHeader"]),
        ]
        table_rows = [headers]

        for m in self.report.mitre_matrix:
            indicators_clean = [_clean_xml(ind) for ind in m.matched_indicators[:2]] if m.matched_indicators else []
            indicators_str = ", ".join(indicators_clean) if indicators_clean else "N/A"
            table_rows.append([
                Paragraph(f"<strong>{_clean_xml(m.technique_id)}</strong>", self.styles["TableCellMono"]),
                Paragraph(f"<strong>{_clean_xml(m.name)}</strong>", self.styles["TableCell"]),
                Paragraph(_clean_xml(m.tactic), self.styles["TableCell"]),
                Paragraph(f"{m.confidence * 100:.0f}%", self.styles["TableCell"]),
                Paragraph(indicators_str, self.styles["TableCell"]),
            ])

        if len(table_rows) == 1:
            table_rows.append([
                Paragraph("N/A", self.styles["TableCell"]),
                Paragraph("No MITRE ATT&CK techniques matched", self.styles["TableCell"]),
                Paragraph("N/A", self.styles["TableCell"]),
                Paragraph("N/A", self.styles["TableCell"]),
                Paragraph("Threat indicators within normal operational baseline.", self.styles["TableCell"]),
            ])

        t = Table(table_rows, colWidths=[65, 120, 95, 60, 200])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), self.c_navy),
            ("BOX", (0, 0), (-1, -1), 0.5, self.c_border),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, self.c_border),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ("LEFTPADDING", (0, 0), (-1, -1), 5),
            ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ]))
        elements.append(t)
        return elements

    def _build_remediation_section(self, width: float) -> List[Any]:
        elements = []
        elements.append(Paragraph("3. Prioritized SOC Remediation Playbook", self.styles["SectionHeading"]))

        headers = [
            Paragraph("Priority", self.styles["TableHeader"]),
            Paragraph("Category", self.styles["TableHeader"]),
            Paragraph("Action Title & Playbook Directives", self.styles["TableHeader"]),
            Paragraph("Target System", self.styles["TableHeader"]),
        ]
        table_rows = [headers]

        for act in self.report.remediation_plan:
            badge_style = self.styles["BadgeP0"] if act.priority == "P0" else self.styles["BadgeP1"] if act.priority == "P1" else self.styles["BadgeP2"]
            p_clean = _clean_xml(act.priority)
            cat_clean = _clean_xml(act.category)
            title_clean = _clean_xml(act.title)
            desc_clean = _clean_xml(act.description)
            target_clean = _clean_xml(act.target_system)
            table_rows.append([
                Paragraph(f"[{p_clean}]", badge_style),
                Paragraph(cat_clean, self.styles["TableCell"]),
                Paragraph(f"<strong>{title_clean}</strong><br/><font color='#475569'>{desc_clean}</font>", self.styles["TableCell"]),
                Paragraph(target_clean, self.styles["TableCell"]),
            ])

        t = Table(table_rows, colWidths=[50, 80, 280, 130])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), self.c_navy),
            ("BOX", (0, 0), (-1, -1), 0.5, self.c_border),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, self.c_border),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 5),
            ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ]))
        elements.append(t)
        return elements

    def _build_findings_and_route_section(self, width: float) -> List[Any]:
        elements = []
        elements.append(Paragraph("4. Evidentiary Findings & Transit Relay Route", self.styles["SectionHeading"]))

        # Findings Table
        headers = [
            Paragraph("Severity", self.styles["TableHeader"]),
            Paragraph("Finding Title", self.styles["TableHeader"]),
            Paragraph("Reason Code", self.styles["TableHeader"]),
            Paragraph("Evidence Description", self.styles["TableHeader"]),
        ]
        table_rows = [headers]

        for f in self.report.evidentiary_findings[:5]:
            sev = _clean_xml(f.get("severity", "medium")).upper()
            title = _clean_xml(f.get("title", "Finding"))
            reason = _clean_xml(f.get("reason_code", "N/A"))
            desc = _clean_xml(f.get("description", "N/A"))
            table_rows.append([
                Paragraph(f"<strong>{sev}</strong>", self.styles["TableCell"]),
                Paragraph(title, self.styles["TableCell"]),
                Paragraph(reason, self.styles["TableCellMono"]),
                Paragraph(desc, self.styles["TableCell"]),
            ])

        if len(table_rows) > 1:
            t = Table(table_rows, colWidths=[65, 135, 110, 230])
            t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), self.c_navy),
                ("BOX", (0, 0), (-1, -1), 0.5, self.c_border),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, self.c_border),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ("LEFTPADDING", (0, 0), (-1, -1), 5),
                ("RIGHTPADDING", (0, 0), (-1, -1), 5),
            ]))
            elements.append(t)

        # Transit Relay Route Summary
        if self.report.transit_route_summary:
            t_map = self.report.transit_route_summary
            hops = t_map.get("hops", [])
            if hops:
                elements.append(Spacer(1, 6))
                elements.append(Paragraph(f"<strong>Relay Hop Transit Chain ({len(hops)} Hops, {t_map.get('total_distance_km', 0):,.0f} km):</strong>", self.styles["BodyDark"]))
                hop_headers = [
                    Paragraph("Hop #", self.styles["TableHeader"]),
                    Paragraph("IP Address", self.styles["TableHeader"]),
                    Paragraph("Location / City / Country", self.styles["TableHeader"]),
                    Paragraph("Autonomous System", self.styles["TableHeader"]),
                    Paragraph("Transit Anomaly", self.styles["TableHeader"]),
                ]
                hop_rows = [hop_headers]
                for h in hops:
                    loc = h.get("location") or {}
                    loc_str = _clean_xml(loc.get("formatted_address") or f"{loc.get('city') or 'Unknown'}, {loc.get('country_name') or 'N/A'}")
                    as_str = _clean_xml(f"AS{loc.get('asn') or 'N/A'} {loc.get('as_org') or ''}")
                    anomaly_str = _clean_xml(h.get("anomaly_reason") or ("Tor Exit" if loc.get("is_tor") else "None"))
                    hop_rows.append([
                        Paragraph(f"#{h.get('hop_number')}", self.styles["TableCellMono"]),
                        Paragraph(_clean_xml(h.get("ip", "N/A")), self.styles["TableCellMono"]),
                        Paragraph(loc_str, self.styles["TableCell"]),
                        Paragraph(as_str, self.styles["TableCell"]),
                        Paragraph(anomaly_str, self.styles["TableCell"]),
                    ])
                t_hops = Table(hop_rows, colWidths=[45, 95, 150, 120, 130])
                t_hops.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#334155")),
                    ("BOX", (0, 0), (-1, -1), 0.5, self.c_border),
                    ("INNERGRID", (0, 0), (-1, -1), 0.5, self.c_border),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("TOPPADDING", (0, 0), (-1, -1), 2),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
                    ("LEFTPADDING", (0, 0), (-1, -1), 4),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                ]))
                elements.append(t_hops)

        return elements

    def _build_ioc_section(self, width: float) -> List[Any]:
        elements = []
        elements.append(Paragraph("5. Deduplicated Indicators of Compromise (IoC) Appendix", self.styles["SectionHeading"]))

        headers = [
            Paragraph("Type", self.styles["TableHeader"]),
            Paragraph("Indicator Value", self.styles["TableHeader"]),
            Paragraph("Severity", self.styles["TableHeader"]),
            Paragraph("Killchain Stage", self.styles["TableHeader"]),
            Paragraph("Context Description", self.styles["TableHeader"]),
        ]
        table_rows = [headers]

        for ioc in self.report.iocs:
            ioc_type_clean = _clean_xml(ioc.ioc_type)
            val_clean = _clean_xml(ioc.value)
            sev_clean = _clean_xml(ioc.severity).upper()
            kc_clean = _clean_xml(ioc.killchain_stage)
            ctx_clean = _clean_xml(ioc.threat_context)
            table_rows.append([
                Paragraph(ioc_type_clean, self.styles["TableCellMono"]),
                Paragraph(val_clean, self.styles["TableCellIocMono"]),
                Paragraph(f"<strong>{sev_clean}</strong>", self.styles["TableCell"]),
                Paragraph(kc_clean, self.styles["TableCell"]),
                Paragraph(ctx_clean, self.styles["TableCell"]),
            ])

        if len(table_rows) == 1:
            table_rows.append([
                Paragraph("N/A", self.styles["TableCell"]),
                Paragraph("No IoCs extracted", self.styles["TableCell"]),
                Paragraph("LOW", self.styles["TableCell"]),
                Paragraph("N/A", self.styles["TableCell"]),
                Paragraph("No external indicators identified.", self.styles["TableCell"]),
            ])

        t = Table(table_rows, colWidths=[60, 185, 50, 95, 150])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), self.c_navy),
            ("BOX", (0, 0), (-1, -1), 0.5, self.c_border),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, self.c_border),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 2),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
            ("LEFTPADDING", (0, 0), (-1, -1), 4),
            ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ]))
        elements.append(t)
        return elements
